services:
  forms-flow-web-root-config:
    container_name: forms-flow-web-root-config
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - NODE_ENV=${NODE_ENV:-production}
        - REACT_APP_API_PROJECT_URL=${REACT_APP_API_PROJECT_URL}
        - REACT_APP_KEYCLOAK_CLIENT=${REACT_APP_KEYCLOAK_CLIENT:-forms-flow-web}
        - REACT_APP_WEB_BASE_URL=${REACT_APP_WEB_BASE_URL}
        - REACT_APP_BPM_URL=${REACT_APP_BPM_URL}
        - REACT_APP_WEBSOCKET_ENCRYPT_KEY=${REACT_APP_WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
        - REACT_APP_KEYCLOAK_URL_REALM=${REACT_APP_KEYCLOAK_URL_REALM:-forms-flow-ai}
        - REACT_APP_KEYCLOAK_URL=${REACT_APP_KEYCLOAK_URL}
        - REACT_APP_APPLICATION_NAME=${REACT_APP_APPLICATION_NAME:-formsflow.ai}
        - REACT_APP_USER_ACCESS_PERMISSIONS=${REACT_APP_USER_ACCESS_PERMISSIONS}
        - REACT_APP_WEB_BASE_CUSTOM_URL=${REACT_APP_WEB_BASE_CUSTOM_URL}
        - REACT_APP_MULTI_TENANCY_ENABLED=${REACT_APP_MULTI_TENANCY_ENABLED:-false}
        - REACT_APP_MT_ADMIN_BASE_URL=${MT_ADMIN_BASE_URL}
        - REACT_APP_MT_ADMIN_BASE_URL_VERSION=${MT_ADMIN_BASE_URL_VERSION}
        - REACT_APP_CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL}
        - REACT_APP_CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED:-false}
        - REACT_APP_DRAFT_ENABLED=${DRAFT_ENABLED:-false}
        - REACT_APP_DRAFT_POLLING_RATE=${DRAFT_POLLING_RATE:-15000}
        - REACT_APP_EXPORT_PDF_ENABLED=${EXPORT_PDF_ENABLED:-false}
        - REACT_APP_PUBLIC_WORKFLOW_ENABLED=${PUBLIC_WORKFLOW_ENABLED:-false}
        - REACT_APP_DOCUMENT_SERVICE_URL=${DOCUMENT_SERVICE_URL}
        - REACT_APP_OPENTELEMETRY_SERVICE=${OPENTELEMETRY_SERVICE:-false}
        - CUSTOM_THEME_URL=${CUSTOM_THEME_URL}
        - FORMSFLOW_WEB_URL=${FORMSFLOW_WEB_URL}
        - FORMSFLOW_NAV_URL=${FORMSFLOW_NAV_URL}
        - FORMSFLOW_SERVICE_URL=${FORMSFLOW_SERVICE_URL}
        - FORMSFLOW_ADMIN_URL=${FORMSFLOW_ADMIN_URL}
        - FORMSFLOW_THEME_URL=${FORMSFLOW_THEME_URL}
    ports:
      - "3000:8080"
    tty: true
