---
apiVersion: v1
kind: Template
labels:
  app: "${APP_NAME}-${INSTANCE}"
  name: "${NAME}-${INSTANCE}"
  role: "${ROLE}"
  template: "${NAME}-${INSTANCE}-template"
metadata:
  annotations:
    description: Mongodb server secret generator.
    tags: "${NAME}-${INSTANCE}"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "${NAME}-${INSTANCE}-secret1"
    stringData:
      admin-password: "${MONGODB_ADMIN_PASSWORD}"
      database-password: "${MONGODB_PASSWORD}"
      database-user: "${MONGODB_USER}"
      NODE_CONFIG: "{\"mongo\": \"mongodb://app:${MONGODB_PASSWORD}@${NAME}-dev:27017/${MONGODB_USER}\"}"
    type: Opaque
parameters:
  - name: NAME
    displayName: Name
    description:
      The name assigned to all of the OpenShift resources associated to the
      server instance.
    required: true
    value: mongodb-formio-core
  - name: INSTANCE
    description: The name of this instance of the application
    displayName: Application Instance Name
    required: true
    value: dev
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together in the OpenShift console.
    required: true
    value: formio
  - name: ROLE
    displayName: Role
    description:
      The role of this service within the application - used for Network
      Policies
    required: true
    value: db
  - name: MONGODB_USER
    displayName: MongoDB Connection Username
    description:
      Username for MongoDB user that will be used for accessing the database.
    required: true
    value: app
  - name: MONGODB_PASSWORD
    displayName: MongoDB Connection Password
    description: Password for the MongoDB connection user.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{32}"
  - name: MONGODB_ADMIN_PASSWORD
    displayName: MongoDB Admin Password
    description:
      Password for the MongoDB administrative account.
    required: true
    generate: expression
    from: "[a-zA-Z0-9]{32}"
