name: Issue Creation Tracker
on:
  issues:
    types: [opened, closed, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Determine Issue Status
      run: |
          if [[ "${{ github.event.action }}" == "opened" ]]; then
            echo "status=ðŸŸ¢ Open" >> $GITHUB_ENV
          elif [[ "${{ github.event.action }}" == "closed" ]]; then
            echo "status=ðŸŸ£ Closed" >> $GITHUB_ENV
          elif [[ "${{ github.event.action }}" == "reopened" ]]; then
            echo "status=ðŸ”µ Reopened" >> $GITHUB_ENV
          else
            echo "status_color=âšª Unknown" >> $GITHUB_ENV
          fi

    - name: Git Issue Details
      run: |
          echo "Issue creator: ${{ github.event.issue.user.login }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue url: ${{ github.event.issue.html_url }}"
          echo "Assigned labels: " ${{ join(github.event.issue.labels.*.name) }}
          echo "Issue status: ${{ github.event.action }}"

    - name: Google Chat Notification
      run: |
          curl --location --request POST '${{ secrets.NOTIFY_GITHUB_ISSUES }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Issue Tracker",
                          "subtitle": "Issue No: #${{ github.event.issue.number }}"
                      },
                      "sections": [
                          {
                              "widgets": [
                                   {
                                     "keyValue": {
                                          "topLabel": "Repository",
                                          "content": "${{ github.repository }}"
                                      }
                                   },            
                                   {
                                     "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "${{ github.event.issue.user.login }}"
                                      }
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assigned Labels",
                                   {
                                     "keyValue": {
                                          "topLabel": "Creator",
                                          "content": "${{ github.event.issue.user.login }}"
                                      },
                                   },
                                   {
                                     "keyValue": {
                                          "topLabel": "Assigned Lables",
                                          "content": "- ${{ join(github.event.issue.labels.*.name) }}"
                                      }
                                   },
                                   {
                                      "textParagraph": {
                                       "text": "Status: ${{ env.status }}"
                                      }
                                   },
                                   {
                                      "buttons": [
                                          {
                                              "textButton": {
                                                  "text": "OPEN ISSUE",
                                                  "onClick": {
                                                      "openLink": {
                                                          "url": "${{ github.event.issue.html_url }}"
                                                      }
                                                  }
                                              }
                                          }
                                      ]
                                  }
                              ]
                          }
                      ]
                  }
              ]
          }'