name: PR Notification to Google Chat

on:
  pull_request_target:
    types: [opened, synchronize, closed]
    branches:
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.base.repo.full_name == 'AOT-Technologies/forms-flow-ai' && github.event.pull_request.draft == false }}

    steps:
      - name: Determine PR Status
        id: pr_status
        run: |
          if [[ "${{ github.event.action }}" == "opened" ]]; then
            echo "status=ðŸŸ¢ Open" >> $GITHUB_ENV
          elif [[ "${{ github.event.action }}" == "closed" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "status=ðŸŸ£ Merged" >> $GITHUB_ENV
          elif [[ "${{ github.event.action }}" == "closed" ]]; then
            echo "status=ðŸ”´ Closed" >> $GITHUB_ENV
          else
            echo "status=ðŸŸ¢ Open" >> $GITHUB_ENV
          fi

      - name: Send notification to Google Chat
        uses: fjogeleit/http-request-action@v1.16.0
        with:
          url: ${{ secrets.PR_NOTIFICATION }}
          method: POST
          contentType: application/json
          data: |
            {
              "cards": [
                {
                  "header": {
                    "title": "Open source: Pull Request Opened by ${{ github.event.pull_request.user.login }}",
                    "subtitle": "Pull Request #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}",
                    "imageUrl": "${{ github.event.pull_request.user.avatar_url }}"
                  },
                  "sections": [
                    {
                      "widgets": [
                        {
                          "textParagraph": {
                            "text": "Repository: ${{ github.repository }}"
                          }
                        },
                        {
                          "textParagraph": {
                            "text": "Status: ${{ env.status }}"
                          }
                        },
                        {
                          "buttons": [
                            {
                              "textButton": {
                                "text": "View Pull Request",
                                "onClick": {
                                  "openLink": {
                                    "url": "${{ github.event.pull_request.html_url }}"
                                  }
                                }
                              }
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }