name: Transition Jira Issue to QA

on:
  pull_request:
    types:
      - closed

jobs:
  transition:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: kiranka123/jira-transition-action@v1